namespace:
  name: demo
 
image:
  repository: nginx
  tag: alpine
  pullPolicy: IfNotPresent

replicaCount: 3

service:
  type: ClusterIP
  port: 8111

resources:
  cpu: 50m
  memory: 256Mi

configMapData: "version:alpine"
