namespace:
  name: prod
 
image:
  repository: nginx
  tag: 1.17.0
  pullPolicy: IfNotPresent

replicaCount: 2

service:
  port: 80

resources:
  cpu: 70m
  memory: 256Mi

configMapData: "version:1.17.0"
